In [1]:
import pandas as pd

In [6]:
df = pd.read_clipboard()
df

      美元[USD]  27.6800  27.7800  27.3400  28.0100
0     港幣[HKD]   3.5290   3.5890   3.3990   3.6050
1     英鎊[GBP]  36.3900  36.7900  35.3600  37.5000
2     日圓[JPY]   0.2418   0.2459   0.2346   0.2473
3     澳幣[AUD]  19.6700  19.9100  19.3900  20.1800
4   加拿大幣[CAD]  21.8600  22.0600  21.4800  22.3900
5   新加坡幣[SGD]  20.2500  20.4300  19.7600  20.6500
6    南非幣[ZAR]   1.7100   1.8100      NaN      NaN
7    瑞典幣[SEK]   3.0100   3.1100      NaN      NaN
8   瑞士法郎[CHF]  29.9500  30.1500  29.2400  30.4300
9     泰幣[THB]   0.8080   0.8500   0.6980   0.8880
10  紐西蘭幣[NZD]  18.7100  18.9100  18.3200  19.1900
11    歐元[EUR]  31.1500  31.5500  30.5300  31.8700
12    韓幣[KRW]      NaN      NaN   0.0219   0.0255
13   馬來幣[MYR]      NaN      NaN   5.5810   7.0220
14   印尼幣[IDR]      NaN      NaN   0.0016   0.0023
15  菲律賓幣[PHP]      NaN      NaN   0.5130   0.6180
16   澳門幣[MOP]      NaN      NaN   3.2100   3.5910
17   越南幣[VND]      NaN      NaN   0.0010   0.0014
18   人民幣[CNY]   4.3460   4.3960   4.2760   4.4380

In [4]:
df.to_csv('cathaybk.csv')